### ISSUE TITLE
Error: Cannot find module 'cst'

### ISSUE THREAD

**Issue by Exelord** [DockYard/ember-suave#123]
Hi, after installation I have this error when I try to use `jscs app/`

```
Error: Cannot find module 'cst'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/travis/build/Selleo/NTFrontend/node_modules/ember-suave/node_modules/jscs-ember-deprecations/lib/rules/disallow-emberkeys.js:2:11)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
```

How can I solve it?

**Comment by brzpegasus** [comment]
See the discussion in #120.

**Comment by brzpegasus** [comment]
The issue appears to be because of `ember-jscs-deprecations`. It declares `jscs` as a [dev dependency](https://github.com/minichate/jscs-ember-deprecations/blob/master/package.json#L32). So upon installing `ember-suave`, the `node_modules` looks like this:

<img width="312" alt="screen shot 2016-06-15 at 3 23 34 pm" src="https://cloud.githubusercontent.com/assets/1691398/16094263/6e2794ee-330d-11e6-9a72-2a8be514a30b.png">

`ember-jscs-deprecations` doesn't download `jscs`. The reason we can circumvent the issue by including `cst` in `ember-suave` is because the dependency lookup will traverse the hierarchy, but I think the real fix needs to happen in `ember-jscs-deprecations`.

**Comment by jrowlingson** [comment]
https://github.com/cst/cst/issues/134
