### ISSUE TITLE
Add a default .jscsrc file

### ISSUE THREAD

**Issue by SaladFork** [dockyard/ember-suave#64]
It would be helpful if the addon included a blueprint for a `.jscsrc` file that would work with most linting plugins. This can be done nicely with the [`additionalRules`](http://jscs.info/overview#additionalrules) and [`preset`](http://jscs.info/overview#preset) options.

I've been using the following:
```json
{
  "additionalRules": ["node_modules/ember-suave/lib/rules/*.js", "lib/rules/*.js"],
  "preset": "./node_modules/ember-suave/lib/jscsrc.json"
}
```

But was hoping to open it up to discussion before submitting a PR.

**Comment by rwjblue** [comment]
:+1:

**Comment by SaladFork** [comment]
Hmm.. this actually breaks `ember s`:
```
$ ember s
version: 1.13.8
Preset "jscsrc" does not exist
AssertionError: Preset "jscsrc" does not exist
    at NodeConfiguration.Configuration._loadPreset (<myapp>/node_modules/ember-suave/node_modules/broccoli-jscs/node_modules/jscs/lib/config/configuration.js:646:5)
    at NodeConfiguration._loadPreset (<myapp>/node_modules/ember-suave/node_modules/broccoli-jscs/node_modules/jscs/lib/config/node-configuration.js:157:45)
    at NodeConfiguration.Configuration._processConfig (<myapp>/node_modules/ember-suave/node_modules/broccoli-jscs/node_modules/jscs/lib/config/configuration.js:490:14)
    at NodeConfiguration.Configuration.load (<myapp>/node_modules/ember-suave/node_modules/broccoli-jscs/node_modules/jscs/lib/config/configuration.js:207:10)
    at StringChecker.configure (<myapp>/node_modules/ember-suave/node_modules/broccoli-jscs/node_modules/jscs/lib/string-checker.js:67:29)
    at Checker.configure (<myapp>/node_modules/ember-suave/node_modules/broccoli-jscs/node_modules/jscs/lib/checker.js:27:39)
    at new JSCSFilter (<myapp>/node_modules/ember-suave/node_modules/broccoli-jscs/index.js:47:15)
    at Class.module.exports.lintTree (<myapp>/node_modules/ember-suave/index.js:12:12)
    at <myapp>/node_modules/ember-cli/lib/broccoli/ember-app.js:468:25
    at Array.forEach (native)
```

I think it's because the addon is now trying to use this `.jscsrc` file and the path is invalid from within `node_modules/ember-suave`.

**Comment by NickChristensen** [comment]
This only breaks because of the jscsrc-builder.js and the temp jscs config file we're building.

I think this should be the default (generating a `.jscsrc` with a blueprint, and consuming the ember-suave rules via `preset`).

##### Benefits:
- Use the `preset` functionality built in to jscs
- Make it immediately apparent where to override rules by creating the `.jscsrc`
- Allow for use outside build process, i.e. editors
- Remove code handling merging config files, checking for existing duplicates, etc, which would...
- Reduce build times

##### Disadvantages:
- Not sure what the migration strategy could be

**Comment by elidupuis** [comment]
Would love to see this! I was just trying to hookup [pre-commit](http://pre-commit.com/) using `ember-sauve`'s default configuration but it can't find the configuration file.

**Comment by hzoo** [comment]
We need to add some preset documentation but I added it to the last release - https://github.com/jscs-dev/node-jscs/releases/tag/v2.1.1

**Comment by scottkidder** [comment]
Since I use syntastic+jscs I wanted this from the moment I installed ember-suave. This is very rough and definitely not ideal. It currently at least breaks the file exclusion for qunit tests since it is completely avoiding the jscsrc-builder. 7aa8a0ac99aec989fc556c7468fec4458c50452a

**Comment by SaladFork** [comment]
Thank you!
