### ISSUE TITLE
Error running rule requireTemplateStringsForConcatenation

### ISSUE THREAD

**Issue by elidupuis** [dockyard/ember-suave#76]
I'm running into a strange issue with the `requireTemplateStringsForConcatenation` rule:

This is the `index.js` file in an ember-addon project; since it doesn't run through Babel I was just going to disable JSCS inline to avoid ES6 errors: 
```
/* jshint node: true */
// jscs:disable
```

When I run `jscs -v index.js` I get the following:

```
requireTemplateStringsForConcatenation: Error running rule requireTemplateStringsForConcatenation: This is an issue with JSCS and not your codebase.
Please file an issue (with the stack trace below) at: https://github.com/jscs-dev/node-jscs/issues/new
TypeError: Cannot read property '_tokenIndex' of undefined
    at Object.JsFile.getNextToken (/Users/eli/.nvm/v0.12.7/lib/node_modules/jscs/lib/js-file.js:318:26)
    at assertIfTokenIsPlus (/Users/eli/showbie/ember-sbe-common/node_modules/ember-suave/lib/rules/require-template-strings-for-concatenation.js:21:30)
    at /Users/eli/showbie/ember-sbe-common/node_modules/ember-suave/lib/rules/require-template-strings-for-concatenation.js:39:7
    at /Users/eli/.nvm/v0.12.7/lib/node_modules/jscs/lib/js-file.js:507:17
    at Array.forEach (native)
    at Object.JsFile.iterateTokensByType (/Users/eli/.nvm/v0.12.7/lib/node_modules/jscs/lib/js-file.js:505:26)
    at Object.module.exports.check (/Users/eli/showbie/ember-sbe-common/node_modules/ember-suave/lib/rules/require-template-strings-for-concatenation.js:19:10)
    at null.<anonymous> (/Users/eli/.nvm/v0.12.7/lib/node_modules/jscs/lib/string-checker.js:165:22)
    at Array.forEach (native)
    at StringChecker._checkJsFile (/Users/eli/.nvm/v0.12.7/lib/node_modules/jscs/lib/string-checker.js:161:31) at index.js :
     1 |/* jshint node: true */
--------^
     2 |// jscs:disable
     3 |'use strict';
```

Interestingly, if the inline `jscs:disable` is moved to the first line in the file I don't get the error!
```
// jscs:disable
/* jshint node: true */
```

Not sure if this is an issue with the custom `requireTemplateStringsForConcatenation` rule or with JSCS itself; figured I'd ask here first.

**Comment by rwjblue** [comment]
These lines need to guard for `previousToken` and `nextToken` being undefined: https://github.com/dockyard/ember-suave/blob/master/lib/rules/require-template-strings-for-concatenation.js#L39-L40

Would you mind submitting a PR wrapping each of those lines in a guard, and adding a new regression test (the example you gave above)?

**Comment by hzoo** [comment]
We have http://jscs.info/rule/requireTemplateStrings in jscs now too if you want to use/modify that

**Comment by rwjblue** [comment]
yes, we should just remove our internal rule (or stop using it in the preset but leave it around for folks that have manually specified it)

**Comment by elidupuis** [comment]
@rwjblue so go ahead with the PR you mentioned? I can take a look in a bit if you'd like.
