### ISSUE TITLE
broccoli-jscs error: Rule "disallowVar" is already registered

### ISSUE THREAD

**Issue by awaer** [dockyard/ember-suave#84]
Ember 2.1.0 w/ `ember-suave` 2.2.0. I just nombom'd and I'm now seeing an error that prevents running `ember serve`. Up until today it has been running fine.

```javascript
{
  "preset": "ember-suave"
}
```

Here is the error when running `ember serve`: 

```javascript
Rule "disallowVar" is already registered
AssertionError: Rule "disallowVar" is already registered
    at NodeConfiguration.Configuration.registerRule (/Projects/Thing/ember/node_modules/ember-suave/node_modules/broccoli-jscs/node_modules/jscs/lib/config/configuration.js:864:5)
    at NodeConfiguration.Configuration._loadAdditionalRule (/Projects/Thing/ember/node_modules/ember-suave/node_modules/broccoli-jscs/node_modules/jscs/lib/config/configuration.js:825:10)
    at NodeConfiguration.<anonymous> (/Projects/Thing/ember/node_modules/ember-suave/node_modules/broccoli-jscs/node_modules/jscs/lib/config/node-configuration.js:213:61)
    at Array.forEach (native)
    at NodeConfiguration._loadAdditionalRule (/Projects/Thing/ember/node_modules/ember-suave/node_modules/broccoli-jscs/node_modules/jscs/lib/config/node-configuration.js:211:61)
    at NodeConfiguration.<anonymous> (/Projects/Thing/ember/node_modules/ember-suave/node_modules/broccoli-jscs/node_modules/jscs/lib/config/configuration.js:502:18)
    at Array.forEach (native)
    at NodeConfiguration.Configuration._processConfig (/Projects/Thing/ember/node_modules/ember-suave/node_modules/broccoli-jscs/node_modules/jscs/lib/config/configuration.js:501:33)
    at NodeConfiguration.Configuration._loadPreset (/Projects/Thing/ember/node_modules/ember-suave/node_modules/broccoli-jscs/node_modules/jscs/lib/config/configuration.js:748:10)
    at NodeConfiguration._loadPreset (/Projects/Thing/ember/node_modules/ember-suave/node_modules/broccoli-jscs/node_modules/jscs/lib/config/node-configuration.js:163:41)
```

Anyone else seeing this?

**Comment by vitch** [comment]
@awaer yep - I'm seeing this too... Yay for SemVer and caret dependencies!

**Comment by jrowlingson** [comment]
Dup of https://github.com/dockyard/ember-suave/pull/81/files

**Comment by vitch** [comment]
See #83 and #81

**Comment by rwjblue** [comment]
Should be resolved now with ember-suave@1.2.3.

**Comment by SaladFork** [comment]
As of `ember-suave@1.2.3` I'm no longer seeing the console error for it or a failing test, but my editor still seems to complain about it:
![disallowVar error](https://i.imgur.com/ugj983z.png)

As well as when manually running `jscs`:
```
$ jscs app -f .jscsrc
```

Using this `.jscsrc`:
```
$ cat .jscsrc
{
  "preset": "ember-suave"
}
```

**Comment by rwjblue** [comment]
@SaladFork - See **Note** in the [release notes](https://github.com/dockyard/ember-suave/releases/tag/v1.2.3):

> Note: Since the globally installed version of JSCS is commonly used by text editor plugins (and many other integration points) you should update the globally installed version of JSCS via the following:
> 
> `npm install -g jscs@2.6.0`

**Comment by SaladFork** [comment]
:facepalm:

Thank you.
